name: DoorProtector
main: DoorProtector\main
version: "2.1.0"
api: 3.0.0
author: narapon
description: ドア保護用プラグインです
commands:
 dp:
  usage: /dp <subcommand>
  aliases: [d]
  description: ドア保護
 setdp:
  aliases: [setd]
  usage: /setdp <subcommand>
  description: §8<OP> ドア保護設定
  permission: setdp.command
permissions:
 setdp.command:
  default: op